<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4daecc53-ed8f-4fc5-b8f5-3f9da43b1f6b</elementGuidId>
    <imagePath></imagePath>
    <name>button_continueToShipping</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/section[1]/main[1]/div[1]/div[2]/div[1]/form[1]/div[1]/div[3]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeLarge\ MuiButton-containedSizeLarge\ MuiButton-root\ MuiButton-contained\ MuiButton-containedPrimary\ MuiButton-sizeLarge\ MuiButton-containedSizeLarge\ css-110xwq5"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'submit') and equals(@text,'CONTINUE TO SHIPPING')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"Continue to shipping\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>CONTINUE TO SHIPPING</value>
        <webElementGuid>bac9ab33-0f9a-46d4-9b2f-b6fcdf0c44ed</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>bac9ab33-0f9a-46d4-9b2f-b6fcdf0c44ed</webElementGuid>
    </webElementProperties>
</WebElementEntity>