<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2e73cdf6-bd8c-4c1a-ab57-1fe637194c67</elementGuidId>
    <imagePath></imagePath>
    <name>link_placeOrder</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[3]/div[1]/div[1]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.btn-anim</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}') and equals(@text,'Place an order')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"Place an order\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>bac9ab33-0f9a-46d4-9b2f-b6fcdf0c44ed</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Place an order</value>
        <webElementGuid>bac9ab33-0f9a-46d4-9b2f-b6fcdf0c44ed</webElementGuid>
    </webElementProperties>
</WebElementEntity>